### ISSUE TITLE
work on names, help exposed in the jenkins gui

### ISSUE THREAD

**Issue by gabemontero** [gabemontero/jenkins-plugin#2]
@bparees and @mfojtik have expressed a need to tweak the names of the tasks exposed and the help surrounding the tasks input fields.

I'll attempt to capture what I gathered via IRC with them, and we can iterate from there.

1)   They were expecting to see a "Trigger deployment".  The existing build step that does this is "Start a deployment in OpenShift".  Shall we simply rename this to ""Trigger a deployment in OpenShift""

2) There was confusion on what "Verify deployments in OpenShift" did.  

Here is the help for the "replicaCount" field:
"  The optional field whose value here should be
  whatever the number of pods you verify the deployment specified in "depCfg" against.
  If not specified it will work with the desired replica count in the DeploymentConfig.  "

Here is the write up on the repo readme:

"determines whether the expected set of DeploymentConfig's, ReplicationController's, and active replicas are present based on prior use of the scaler (2) or deployer (3) steps"

Perhaps a more literal, detailed explanation of the what the code does is what is needed.  I'll post that here as the first foray in addressing the documentation issue:
- it first confirms the specified deployment config exists
- it then gets the list of all replication controllers for that DC, and finds the latest incarnation
- and then for up to 3 minutes, it sees if the current replica count is at least equal to the desired replica count.

3) the replica count for the scaler is unclear when the count is 0/unspecified.  Looking at the help, yes, this seems obviously lacking to me as well.  The write up in the readme is only marginally better:

""Scale deployments in OpenShift": performs the equivalent of an oc scale command invocation; the number of replicas is specified as a parameter to this build step, and the plugin will confirm whether the desired number of replicas was launched in a timely manner"

My initial proposal for the help:  "The value here should be whatever the number of pods you want started for the deployment specified in "depCfg". It is the equivalent of the value supplied to `--replicas` with an `oc scale` command invocation.  This is a required parameter.  If an integer is not specified here, this build step can not be added to the job.  Note: specifying a 0 is allowed, and means you do not want any pods for the specified deployment config running."

**Comment by bparees** [comment]
ok so separately it seems we still need an "oc deploy --latest" equivalent step that will trigger a (re)deployment of a DC.  Currently @mfojtik is hacking that by doing a scale to 0, then scale back up, but triggering a deploy is the right approach.  (the only challenge with trigger a deploy is you then need to also validate that deploy succeeded to know the new image is running, not the old one.  So maybe a "Check Deployment Success"(kinda like Checking Build Success) step is also in order.  That might be a more useful version of the current "verify deployment" feature.

**Comment by gabemontero** [comment]
I believe the formerly "Start a deployment in OpenShift", now "Trigger a deployment in OpenShift", was essentially, or *almost*" doing the equivalent of --latest=true.  If correct, I think it just needs a minor tweak to accomplish full equivalence to --latest=true even when starting from scratch.

**Comment by gabemontero** [comment]
Yep ... I think its working.  Will deliver in a sec to jenkins-ci.

**Comment by gabemontero** [comment]
along with the proposed doc changes in the description.  I'll look into the "check deployment success" evolving from "verify deployment" on Tuesday.

**Comment by mfojtik** [comment]
@gabemontero I think our goal should be to use the same terminology as we do in OpenShift (openshift docs)

**Comment by gabemontero** [comment]
Yep - which is why i did a 'oc help deploy' and it says "Start" a
deployment, not "Trigger" one which lead to my original choice there.  Pending
our deciding what to do about that specific item certainly i can continue
and go back and cross ref with existing help and doc.  Please point out
when you can specific items which are not in sync.

**Comment by gabemontero** [comment]
In investigating "Check Deployment Success" I found an issue with the deployer where it was not honoring running deployments.  It now follows the same logic as https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/deploy.go#L212-L221

Change delivered to https://github.com/mfojtik/jenkins-ci and https://github.com/gabemontero/jenkins/tree/jenkinsRD

**Comment by gabemontero** [comment]
So I've been iterating over the "the only challenge with trigger a deploy is you then need to also validate that deploy succeeded to know the new image is running, not the old one" portion of the earlier statement from @bparees about "Check Deployment Success".

In running the various incarnations of `oc deploy <dep cfg name>` with `--loglevel=8` logging, and exploring the end-to-end cli code paths, what I found that seemed *potentially* relevant here included:

1) inspect/increment when needed/compare the latest version fields of the deployment config and replication controller (the current verification step does this today)

2) if the deployment is initially inactive, and you are just doing a display, there is interrogation of the deployment config to see if it has any config or image triggers for customizing the informational message ... do we want to handle this special case  and provide a similar information message in "Check Deployment Success" 

3) checking of the `openshift.io/deployment.phase` annotation on the latest replication controller, to see if the deployment is completed / failed / in-progress ... is verifying this annotation's value is [this](https://github.com/openshift/origin/blob/master/pkg/deploy/api/types.go#L21) sufficient ?  I'm thinking yes, but please confirm.

Please confirm as well: is the current check of seeing that the current replica count gets up to the desired replica count unnecessary?

**Comment by gabemontero** [comment]
Also, the deployer still isn't quite in line with `oc deploy --latest`.  The cli only halts subsequent deploys if the current one is still pending per the deployment.phase annotation.  I'll correct and update in short order.

**Comment by bparees** [comment]
>  inspect/increment when needed/compare the latest version fields of the deployment config and replication controller (the current verification step does this today)

so we actually have to replicate the client-side logic to create the deployment, there's no simple api endpoint to just trigger the deployment and let it compute the version/rc_count/etc?  that's unfortunate.


>  do we want to handle this special case and provide a similar information message in "Check Deployment Success" 

can you give an example of this message?  i'm not familiar with what it says offhand to say whether or not we'd want to mimic it.

> is verifying this annotation's value is this sufficient ? I'm thinking yes, but please confirm.
looks right

> Please confirm as well: is the current check of seeing that the current replica count gets up to the desired replica count unnecessary?

yes i'd say the deploy is not complete until the RC count is reached.  Maybe it should be a checkbox option on the plugin (wait for all replicas vs wait for at least one replica)

**Comment by gabemontero** [comment]
Thanks for the clarifications.  Answers to questions embedded.

On Fri, Oct 9, 2015 at 9:31 AM, Ben Parees <notifications@github.com> wrote:

> inspect/increment when needed/compare the latest version fields of the
> deployment config and replication controller (the current verification step
> does this today)
>
> so we actually have to replicate the client-side logic to create the
> deployment, there's no simple api endpoint to just trigger the deployment
> and let it compute the version/rc_count/etc? that's unfortunate.
>
Yep, aside from examining the client-side flow, searching on the refs to
[DeploymentConfig.LatestVersion](
https://github.com/openshift/origin/blob/master/pkg/deploy/api/types.go#L248),
the controller only
seems to deal with it either by config or image change.


> do we want to handle this special case and provide a similar information
> message in "Check Deployment Success"
>
> can you give an example of this message? i'm not familiar with what it
> says offhand to say whether or not we'd want to mimic it.
>
Sure, with the jenkins image for example, after starting everything up, if
I execute `oc deploy frontend` prior to starting any builds, I get
`frontend #1 deployment waiting on image or update`.
That string is dynamically constructed, where `on image` is included if
there is an image change trigger defined on the deployment config, and `or
update` is added if there is a config change trigger.
Also, if there is only a config change trigger, it would just add `on
update`.


> is verifying this annotation's value is this sufficient ? I'm thinking
> yes, but please confirm.
> looks right
>
> Please confirm as well: is the current check of seeing that the current
> replica count gets up to the desired replica count unnecessary?
>
> yes i'd say the deploy is not complete until the RC count is reached.
> Maybe it should be a checkbox option on the plugin (wait for all replicas
> vs wait for at least one replica)
>
OK, I'll add config options so the user can tun how many replicas to wait
for (where the default is all).

**Comment by bparees** [comment]
> Sure, with the jenkins image for example, after starting everything up, if I execute `oc deploy frontend` prior to starting any builds, I get `frontend #1 deployment waiting on image or update`. That string is dynamically constructed, where `on image` is included if there is an image change trigger defined on the deployment config, and `or update` is added if there is a config change trigger. Also, if there is only a config change trigger, it would just add `on update`.

hm.  that's a strange message.  waiting on image makes sense if the image it's supposed to deploy with doesn't exist yet, but waiting on update(config change) doesn't make sense to me if the deployment has already been triggered/created.

either way i'm worried you're going to have to replica a lot of oc deploy logic to get there...(as it is i'm worried about how much you're going to have to replica...  does the client side logic do all the introspection to see that there's an imagechangetrigger and look up the image it corresponds to if so, then substitute that image into the Container definition for the RC it creates?  we should make sure @danmace takes a look at what you do here)

**Comment by gabemontero** [comment]
On Fri, Oct 9, 2015 at 1:55 PM, Ben Parees <notifications@github.com> wrote:

> Sure, with the jenkins image for example, after starting everything up, if
> I execute oc deploy frontend prior to starting any builds, I get frontend
> #1 deployment waiting on image or update. That string is dynamically
> constructed, where on image is included if there is an image change
> trigger defined on the deployment config, and or update is added if there
> is a config change trigger. Also, if there is only a config change trigger,
> it would just add on update.
>
> hm. that's a strange message. waiting on image makes sense if the image
> it's supposed to deploy with doesn't exist yet, but waiting on
> update(config change) doesn't make sense to me if the deployment has
> already been triggered/created.
>
> either way i'm worried you're going to have to replica a lot of oc deploy
> logic to get there...(as it is i'm worried about how much you're going to
> have to replica... does the client side logic do all the introspection to
> see that there's an imagechangetrigger and look up the image it corresponds
> to if so, then substitute that image into the Container definition for the
> RC it creates? we should make sure @danmace <https://github.com/danmace>
> takes a look at what you do here)
>

OK, it was a minor aspect of the possibilities, and one I was not as
inclined to do (and have not done yet).  Just wanted to surface what `oc`
was currently (and to your question, yes, it does a fair amount of
introspection to determine that stuff).  Let's officially punt on this then.

Certainly we can still review with others down the line as needed.

**Comment by bparees** [comment]
> OK, it was a minor aspect of the possibilities, and one I was not as inclined to do (and have not done yet). Just wanted to surface what `oc` was currently (and to your question, yes, it does a fair amount of introspection to determine that stuff). Let's officially punt on this then.

to be clear, you are still going to have to do the logic to see if the DC has an imagechangetrigger and if so, look up the current image for the ICT and define the new deployment in terms of that image rather than using the existing Container image field.

**Comment by gabemontero** [comment]
Yep - roger that.

**Comment by gabemontero** [comment]
An outline on the (potential) approach to DC / ICT / Image confirmation piece.  I'll start coding to this, but certainly can shift gears based on comments.  Note, if any step "fails", deployment verification fails:

- taking the latest RC the deployment verifier is already interrogating for replicas
- the DC is stored as an annotation on the RC
- inside "status", specifically the causes list, there should be a ImageChange cause, where the image tag is listed (i.e. ":latest")
- then go down the DC's triggers list; find the ImageChange trigger whose lastTriggerImage root matches the image, but also has the fully qualified hexadecimal image ID instead of ":latest" ... save that hex image
- then find the prior RC, and from its DC annotation, get the latestTriggerImage for the image in question
- compare the hexadecimal image IDs, confirm they are different

**Comment by bparees** [comment]
Sounds too ict specific. Not all DCs have an ict.

Is this just for deployment verification or is this flow also related to
deployment triggering?

Ben Parees | OpenShift

**Comment by gabemontero** [comment]
I was just thinking deployment verification

**Comment by gabemontero** [comment]
In case it helps, items from previous comments I zero'ed in on in augmenting the check deployment / verify deployment step:
- "you then need to also validate that deploy succeeded to know the new image is running, not the old one"
- "do the logic to see if the DC has an imagechangetrigger and if so, look up the current image for the ICT and define the new deployment in terms of that image rather than using the existing Container image field"

**Comment by bparees** [comment]
That second bullet was about creating new deployments though.

Isn't just getting the current rc from the dc sufficient to know which rc
needs to be validated(ie that it's the current one) and then it's just a
matter of counting active replicas?

Ben Parees | OpenShift

**Comment by gabemontero** [comment]
Getting the current rc, counting active replicas, etc. is what the "Check deployment success in OpenShift" build step (used to be called "Verify deployments in OpenShift") has been doing (and has for a while).  Hopefully the updated readme at https://github.com/gabemontero/openshift-jenkins-buildutils helps clarify that.

Also, forgot to clarify earlier, my current prototype accounts for the fact that ImageChangeTriggers are not required.  The validation does NOT fail things if there are no ICTs.

Regarding where the "check ICT, validate image change, etc." logic should live, if your clarification re: "about creating new deployments" implies not embedding it in the verification step but instead in the existing "Perform builds in OpenShift" build step (i.e. the`oc start-build` equivalent ... the "trigger deloyment" or `oc deploy --latest` actually won't change the image, right? ... I didn't think it would, and it isn't in my testing), I could go either way, or I could even go with including that logic both in the `oc start-build` equivalent (again with the caveat that it will bypass failing the job if the ICTs exist) as well as having a separate build step, a "Verify Image Change", if customer want to validate new image versions getting imported into the image streams or into docker.io, etc. 

Thoughts / anything close to agreement ;-) ?

**Comment by gabemontero** [comment]
After iterating of this some today, I've shifted a tad from last night, but I don't think much ...where I landed is:
- the "Check deployments .." solely gets the current rc and verifies the count of active replicas as discussed earlier here / what has been doing previously
- I've tied the image verification logic to the "Perform builds in OpenShift" and "Get latest OpenShift build status" build steps
- what the logic does:
a) looks at the build config referenced in those 2 Jenkins "build steps"
b) if the build config outputs an image, it grabs the image tag (otherwise it punts and allows the step to pass)
c) if then polls all deployment configs, looking for any that have image change triggers referencing the image tag pulled from the build config output (if no dc's are found with such triggers, it let's the build pass)
d) if then polls those dcs with triggers, see if they triggered because of image change, waits for their latest deployment to complete, and then compares the imageFromTrigger for the latest RC and the previous RC, and confirms if the image is different based in the image hex id
e) if all dcs with these triggers pass, we let the build step pass; if any fail, we fail the build step

**Comment by bparees** [comment]
check deployments makes sense.

For the image verification function, let me see if i've got the use case right..this would be for when a user wants to ensure that an openshift build runs, produces a new image, and that new image has been deployed?

lastly, there is still a "trigger a new deployment" (equivalent to "oc deploy --latest") function coming? 
(sorry if it's already in here somewhere, i've been mostly keeping up with this on my phone intermittently the last few days so my responses have been sub-par)

**Comment by gabemontero** [comment]
On Thursday, October 15, 2015, Ben Parees <notifications@github.com> wrote:

> check deployments makes sense.
>

Ok great

> For the image verification function, let me see if i've got the use case
> right..this would be for when a user wants to ensure that an openshift
> build runs, produces a new image, and that new image has been deployed?
>

Yes sir that is the gist

> lastly, there is still a "trigger a new deployment" (equivalent to "oc
> deploy --latest") function coming?
> (sorry if it's already in here somewhere, i've been mostly keeping up with
> this on my phone intermittently the last few days so my responses have been
> sub-par)
>

Yep it has already arrived as mentioned here before - and no worries ( I am
glad you have at least avoided opening your lap top during PTO :-) )

**Comment by gabemontero** [comment]
going to close this one out - as the work hear has met the original purpose; we can continue to iterate over the jenkins plugin with subsequent issues once it falls under github.com/openshift
